### Load in Numpy

In [2]:
import numpy as np

### The Basics

In [33]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [13]:
b = np.array([[9.0, 8.0, 7.0],[5.0, 4.0, 3.0]])
print(b)

[[9. 8. 7.]
 [5. 4. 3.]]


In [15]:
# Get Dimension
a.ndim

1

In [21]:
# Get Shape
b.shape

(2, 3)

In [35]:
# Get Type 
a.dtype

dtype('int16')

In [51]:
# Get Size
a.itemsize # in bytes

2

In [47]:
# Get total size (a.size gives item count)
# a.size * a.itemsize
a.nbytes

6

### Accessing / Changeing sepecifig elements, rows, columns, etc

In [58]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [60]:
# Get a specific element [r, c]
a[1,5]

13

In [68]:
# Get a specific row
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [70]:
# Get a specific column
a[:, 3]

array([ 4, 11])

In [76]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[1, 1:-1:2]

array([ 9, 11, 13])

In [82]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3D example

In [88]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [121]:
# Get specific element (work outside in) [matrix_no, row, column]
b[0,1,1]

4

In [126]:
# Replace 
b[:, 1, :] = [[9, 9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [142]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [150]:
# All 1s matrix
np.ones((2,2), dtype = 'int32')

array([[1, 1],
       [1, 1]])

In [152]:
# Any other number
np.full((2,2), 99, dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [154]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [160]:
# Random decimal numbers
np.random.rand(4,2)
np.random.random_sample(a.shape) # copies the shape of variable 'a' and fills the shape with random numbers

array([[0.99825747, 0.4927249 , 0.10690009, 0.99183438, 0.54016228,
        0.71594813, 0.3202911 ],
       [0.32014727, 0.39266203, 0.91716732, 0.93876052, 0.07828601,
        0.83571966, 0.45504719]])

In [186]:
# Random integer values
np.random.randint(-4, 8, size=(3,3))

array([[ 1,  0, -2],
       [ 5,  4,  4],
       [-2, -4,  5]])

In [190]:
# Identity matrix
np.identity(5, dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [204]:
arr = np.array([[1,3,4]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 3 4]
 [1 3 4]
 [1 3 4]]


In [219]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays!

In [217]:
a = np.array([1,2,3])
b = a.copy()  # without copy(), address of a and b remain same. This results to change of one variable reflecting to other variable
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematics

In [234]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [236]:
a + 2

array([3, 4, 5, 6])

In [238]:
a - 2

array([-1,  0,  1,  2])

In [240]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [250]:
a * 2

array([2, 4, 6, 8])

In [252]:
a ** 2

array([ 1,  4,  9, 16])

In [246]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [255]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#### Linear Algebra